POST https://thebetter.bsgroup.eu/Authorization/SignIn HTTP/1.1
Content-Type: application/json

{}

###
POST https://thebetter.bsgroup.eu/Users/GetProfile HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.uYiYtKCL5UvCszAebLuQuA7eQxKlz2LlqDNE4-jAHZ8TVAvu75oKkA.CV-tD8MiNE4WyS8cuvwsPA.UTrPlEng3SrgRz_pDjNBtNxMtLOQqtnkuvzsCycuxVG4Dzc9yHNzJ9RXCurDrc24XbyDqFOgIWXjAobGRrzGdgS8JHuqoSrvdOMvmUFFoC1pVhEf-0A5dTon5Xf0R1AeGB-a13nLL18A4JubehidDBmztT1gqeC__AZa1RTzDligduaZer5MDG5paybVl9HH3uTMTHeZFMaZHmwy_F_XoDV3UlS-slHjqZdXYe4yorVSOJkEUJFVuBSRN6rNP88Fu8QSFTnxx7g0Zu5UorJbjbZOvtBEcBNlD1BVkya9EcPAG8ZxkEn-f_Vl9OIPN_OAHVfv_nrGNfCCOZI_WfqfZ8cmy-zBhfuUy-mqMuYMdLOSs13bqjMk846wRJxfAbwzQpMHBtD0W4A0vSy9GnclrA8_q11vprss839eMY2kz0-jgo6eYOjDBR3IeOs4ur2QjX4kNWMhOqMxYmOiSKMr41t71tgccF4aCDd4lqKPPgYLai0tbbN_QsYEz8-Op2SUPjBysnYnkRiTCcZ8gniilYOTwqF5EVID7rCBBDQgmxlj7wLVIN5mfKFjA7gDgSXfUqociImrdo20rI_hTgb18w.qKvVweRUXA4CebbPRCQC0A

{
  "IncludeBranding": true,
  "IncludeUploadFilesInfo": true
}
